import { GoogleGenerativeAI } from '@google/generative-ai';
import { Octokit } from '@octokit/rest';
import { nanoid } from 'nanoid';
import fs from 'node:fs/promises';

const apiKey = process.env.GEMINI_API_KEY;
const auth = process.env.GH_AUTH;
const repoFull = process.env.GH_REPO;
const mission = process.env.MISSION;
const baseBranch = process.env.BASE_BRANCH || 'main';
const modelName = process.env.MODEL || 'gemini-3.5-flash';

if (!apiKey) throw new Error('Missing GEMINI_API_KEY secret');
if (!auth) throw new Error('Missing GitHub workflow token');
if (!repoFull) throw new Error('Missing repository name');
if (!mission) throw new Error('Missing mission');

const [owner, repo] = repoFull.split('/');
const gh = new Octokit({ auth });
const genAI = new GoogleGenerativeAI(apiKey);
const model = genAI.getGenerativeModel({
  model: modelName,
  systemInstruction: 'You are a careful senior engineer. Return strict JSON only. Generate useful repository files for the requested product. Do not include secrets.',
  generationConfig: { responseMimeType: 'application/json' }
});

const branch = `cloud-agent/${Date.now()}-${nanoid(5)}`;
const baseRef = await gh.git.getRef({ owner, repo, ref: `heads/${baseBranch}` });
await gh.git.createRef({ owner, repo, ref: `refs/heads/${branch}`, sha: baseRef.data.object.sha });

const prompt = `Create a focused implementation for this repository mission.\n\nMission:\n${mission}\n\nReturn JSON with this exact shape:\n{\n  "summary": "short summary",\n  "files": [\n    {"path":"relative/path.ext", "content":"complete file content"}\n  ]\n}\n\nRules:\n- Keep paths relative.\n- Do not write credentials.\n- Include practical code, README notes, and tests or workflow files when useful.\n- Prefer small but complete files.`;

const response = await model.generateContent(prompt);
let plan;
try {
  plan = JSON.parse(response.response.text());
} catch (error) {
  await fs.writeFile('agent-raw-output.txt', response.response.text());
  throw new Error('Model did not return valid JSON. Raw output saved as artifact candidate.');
}

const files = Array.isArray(plan.files) ? plan.files : [];
if (files.length === 0) throw new Error('Model returned no files');

for (const file of files.slice(0, 30)) {
  if (!file.path || typeof file.path !== 'string') continue;
  if (file.path.startsWith('/') || file.path.includes('..')) continue;
  const content = String(file.content ?? '');
  let sha;
  try {
    const existing = await gh.repos.getContent({ owner, repo, path: file.path, ref: branch });
    if (!Array.isArray(existing.data) && existing.data.sha) sha = existing.data.sha;
  } catch {}
  await gh.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: file.path,
    branch,
    message: `cloud-agent: update ${file.path}`,
    content: Buffer.from(content).toString('base64'),
    sha
  });
}

const pr = await gh.pulls.create({
  owner,
  repo,
  head: branch,
  base: baseBranch,
  title: `Cloud agent: ${mission.slice(0, 70)}`,
  body: `Mission:\n${mission}\n\nSummary:\n${plan.summary || 'Generated by cloud-agent workflow.'}\n\nGenerated branch: ${branch}`
});

console.log(`PR opened: ${pr.data.html_url}`);
